INSERT INTO Marcas (nombre, pais, anno_creacion)
VALUES 
('SpaceX', 'Estados Unidos', 2002),
('NASA', 'Estados Unidos', 1958),
('ESA (European Space Agency)', 'Europa', 1975),
('Roscosmos', 'Rusia', 1992),
('CNSA (China National Space Administration)', 'China', 1993),
('ISRO (Indian Space Research Organisation)', 'India', 1969),
('JAXA (Japan Aerospace Exploration Agency)', 'Japón', 2003),
('ULA (United Launch Alliance)', 'Estados Unidos', 2006),
('Blue Origin', 'Estados Unidos', 2000),
('Boeing Defense, Space & Security', 'Estados Unidos', 1952),
('Lockheed Martin', 'Estados Unidos', 1912),
('Orbital Sciences Corporation', 'Estados Unidos', 1982),
('SpaceDev', 'Estados Unidos', 1997),
('Bigelow Aerospace', 'Estados Unidos', 1999),
('Space Adventures', 'Estados Unidos', 1998),
('Spacehab', 'Estados Unidos', 1984),
('SpaceX Japan', 'Japón', 2018),
('ExPace', 'China', 2015),
('Rocketspace', 'Estados Unidos', 2010),
('Virgin Galactic', 'Reino Unido', 2004),
('Mitsubishi Heavy Industries', 'Japón', 1954),
('Korea Aerospace Industries', 'Corea del Sur', 1999),
('Arianespace', 'Francia', 1980),
('International Launch Services', 'Estados Unidos', 1995),
('Sea Launch', 'Estados Unidos', 1995),
('Proton-M', 'Rusia', 1965),
('Soyuz-2', 'Rusia', 2004),
('Long March', 'China', 1970),
('Antares', 'Estados Unidos', 2008),
('Delta IV', 'Estados Unidos', 2002),
('Atlas V', 'Estados Unidos', 2002),
('Falcon 1', 'Estados Unidos', 2006),
('Falcon 9', 'Estados Unidos', 2010),
('Falcon Heavy', 'Estados Unidos', 2018),
('H-IIA', 'Japón', 2001),
('H-IIB', 'Japón', 2009),
('Ariane 5', 'Francia', 1996),
('Vega', 'Francia', 2012),
('Zenit', 'Ucrania', 1985),
('Angara', 'Rusia', 2014),
('Chang Zheng', 'China', 1970);